# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mpp.lampungtimurkab.go.id CI

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]
    env:
      NEXT_PUBLIC_API_URL_MPP: https://backend-mpp.newus.id/api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name : Run NPM
      working-directory: ./mpp-mobile
      run: npm ci
    - name : Run build
      working-directory: ./mpp-mobile
      run: npm run build --if-present
    - name : change repo
      run : pm2 restart 8
