name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]
    env:
      NEXT_PUBLIC_API_URL_MPP: https://backend-mpp.newus.id/api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name : Run NPM
      working-directory: ./mpp-mobile
      run: npm i
    - name : Run build
      working-directory: ./mpp-mobile
      run: npm run build --if-present
    - name : change repo
      run : cd /home/newus-mppdigital/htdocs/mppdigital.newus.id/mpp-mobile/actions-runner/_work/mpp-web-fe/mpp-web-fe/mpp-mobile
    - run : pm2 restart mppdigital.newus.id
    

    
    
