name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name : NVM use 22
      run : nvm use 22
      working-directory: mpp-mobile
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Install and Build mpp-web-fe
      run: |
        git pull origin main
        npm install
        npm run build
      working-directory: mpp-web-fe
    
    - name: Install and Build mpp-mobile
      run: |
        git pull origin main
        npm install
        npm run build
      working-directory: mpp-mobile
    
    - name: Restart PM2 Service
      run: pm2 restart mppdigital.newus.id

    - name: Run Tests mpp-web-fe
      run: npm test
      working-directory: mpp-web-fe

    - name: Run Tests mpp-mobile
      run: npm test
      working-directory: mpp-mobile
